version: '3.7'
services:
  backend:
    build:
      context: ./backend
    container_name: flask_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/my-react-app
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
  db:
    image: postgres:12-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_DB=restoran
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
volumes:
  db_data:
